### ISSUE TITLE
Search function in API reference not working as expected

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjsframework.github.io#1]
as per @hlevring

http://321.tv/v?f77d565447ed13ef2a92bcbffdf10323.flv

**Comment by dcefram** [comment]
The search function currently only supports searching Classes/modules. Methods are not yet supported, but I believe we can add that up.

I checked the code of the generator, I believe I can add symbols to the array that is used by the search module

**Comment by hlevring** [comment]
Sound good...would be nice to use the search to find methods when we have some idea of a possible  sub string in a method name.

**Comment by dcefram** [comment]
Yup, the search module currently uses regex to for searching, so that would already be handled once I get the generator to automatically add method names to the datalist that the search module uses.

**Comment by dcefram** [comment]
The latest generator would now include method names. I also updated the search functionality to make use of such data.

All of these updates will be implemented once xjs version 0.8.0 is out

**Comment by Matrim-Cauthon** [comment]
This should already be accomplished in latest docs: 0.8.0 release.

Not sure how long github.io caches pages but this item can be closed now.
