### ISSUE TITLE
Update tutorial on authentication best practice

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjsframework.github.io#11]
As of internal build XBC 2.7.1511.1902, it is now possible to get a hash of the logged-in user's identity. We need to update our tutorials to include using this functionality to properly distinguish authentication info granted to different users.

Functions will be created in [xjs#32](https://github.com/xjsframework/xjs/issues/32)

**Comment by dcefram** [comment]
I think the tutorials are good to go. We could however change the links of getUserIdHash().

Current link: `http://xjsframework.github.io/api.html#/core/App`
Suggested link: `http://xjsframework.github.io/api.html#/core/App#getUserIdHash`

This will automatically scroll the page to wherever getUserIdHash's description/details is. The same suggestion goes for links to `createDialog`, `Dialog.return`, and `getResult()`
