### ISSUE TITLE
Document suggested pattern for initializing a source

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjsframework.github.io#16]
We will need to create a tutorial (or we can possibly use quick start as well, let's find a logical place for this) where we can explain our "one-time-only" initialization for sources.

Example: a source which attempts to make itself "full-screen" should only do so once. It shouldn't try doing it on refresh, or when the application restarts, in order to preserve any user settings.

**Comment by Matrim-Cauthon** [comment]
This will be important for xjsframework/xjs#85 as initialization will become a bit tricky when global sources are involved.

**Comment by Matrim-Cauthon** [comment]
@virn for this one, @SML-MeSo can give more details.

Make sure to update all relevant parts in the tutorials section to reflect these changes. You can coordinate the changes in this item together with #17 so that everything is cohesive.

**Comment by virn** [comment]
@SML-MeSo I've made the changes on this together with #17. Kindly review the change and possible things that I've missed.

**Comment by Matrim-Cauthon** [comment]
Here are some changes that need to be done for this section of the tutorial (this does not include the rest of the page that is for #17):
- `Item.getItemList` returns an array of `Item`s. 
- Let's make it clearer that the configuration object is a _source-level property_, so that calling `loadConfig` on an `Item` makes the call bubble up to the underlying source
- We need to more clearly explain that we can set initial code _renderer/item-level properties_ (such as positioning the renderer/video item to take the entire stage) but this should only work reliably when the source is not made global yet
- Optional: maybe also show actual initialization code that uses only item-level properties, which will mean that we want to set a dummy value inside the configuration object? Confirm with @SML-MeSo on this once the above changes are done
