### ISSUE TITLE
Document new source/item paradigm

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjsframework.github.io#17]
Moving forward we'll need to clearly explain what's the big deal with xjsframework/xjs#85. This will involve explaining how developers should interact with sources and video items, etc.

We will need to document some kind of "migration guide" from older versions as well.

**Comment by Matrim-Cauthon** [comment]
@virn please collaborate with @dcefram on this one.

**Comment by virn** [comment]
@dcefram kindly review the changes here.

**Comment by Matrim-Cauthon** [comment]
@virn I've modified the tutorial at commit 6a4f1d9.

Please review the changes and see the fixes and amendments. Please gather a list of item-level properties (properties specific to the renderer part only) and add a Renderer Properties section listing them and their relevant function calls. This way, it's much clearer which functions do not "bubble up" to the source.
