### ISSUE TITLE
Remote debug will not work with the latest release of Chrome (Chrome 50)

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjsframework.github.io#20]
Chrome 50 removed support for `Object.observe`, which is used by CEF's devTools. There's currently no fix on CEF side for this, so we'll have to specify what other developers can use to debug their plugin IF their Chrome auto-updated to 50 or they manually updated to 50 (because it's the latest one *duh*).

- Use a cefbuild that is lower than 50 (https://cefbuilds.com - Branch 2623)
- Add the remote debug URL as an extension of XSplit. _This works! lol_

**Comment by Matrim-Cauthon** [comment]
Let's add this to our debugging tutorial. Shouldn't be too long anyways. cc @SML-MeSo

**Comment by Matrim-Cauthon** [comment]
Putting this back on Review, let's make sure the text is very very visible (maybe move it to the top of a page?) before releasing
