### ISSUE TITLE
Some API description is rendered inside <pre> tags

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjsframework.github.io#9]
http://xjsframework.github.io/api.html#/window/SourceConfigWindow#useFullWindow

The first line of the comments is always rendered as a code by the document generator, unless it's a one line comment.

**Comment by Matrim-Cauthon** [comment]
At the moment I did this quick fix, but I'm not sure if there are better ways to modify the doc gen for this kind of documentation. Perhaps this is sufficient.
